---
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$_IMAGE_TAG"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$_IMAGE_TAG"
images:
  - "gcr.io/$PROJECT_ID/$REPO_NAME:$_IMAGE_TAG"
