-- Query auto-generated by GLAM
-- For more info on tables referenced in this query see:
-- https://dictionary.telemetry.mozilla.org/apps/firefox_desktop/pings/metrics

<% if (!normalized) { %>
CREATE TEMP FUNCTION hist_sum(entries ARRAY<STRUCT<key STRING, value INT64>>) AS (
  ARRAY(SELECT AS STRUCT key, CAST(SUM(value) AS FLOAT64) AS value FROM UNNEST(entries) GROUP BY key ORDER BY key)
);
<% } %>

WITH pre_aggregates AS (
  SELECT
    <% if (normalized) { %>mozfun.glam.histogram_normalized_sum(
      ARRAY_CONCAT_AGG(metrics.${metric_type}.${metric_name}.values),
      ${sample_mult}
    ) AS aggregates,<% } else { %>hist_sum(
      ARRAY_CONCAT_AGG(metrics.${metric_type}.${metric_name}.values)
    ) AS aggregates,<% } %>
    "${metric_type}" AS metric_type,
    COALESCE(
      SAFE_CAST(SPLIT(client_info.app_display_version, '.')[OFFSET(0)] AS INT64),
      0
    ) AS app_version,
    SUBSTR(client_info.app_build, 0, 10)AS app_build_id,
    COUNT(distinct client_info.client_id) AS client_count
FROM
  `moz-fx-data-shared-prod.firefox_desktop.metrics` -- Currently only supports Metrics ping
WHERE
  DATE(submission_timestamp) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 14 DAY) AND CURRENT_DATE
  AND SUBSTR(client_info.app_build, 0, 10) >= FORMAT_DATE("%Y%m%d", DATE_SUB(CURRENT_DATE, INTERVAL 14 DAY))
  <% if (os == '*') { %> -- AND client_info.os = "Windows" -- Remove to filter by OS<% } else { %>AND client_info.os = "${os}"<% } %>
  AND client_info.client_id IS NOT NULL
  AND client_info.app_channel = "${channel}"
  AND sample_id BETWEEN 0 AND ${sample_size}
  AND metrics.${metric_type}.${metric_name}.values IS NOT NULL
GROUP BY metric_type, app_version, app_build_id
),
percentiles_agg AS (
  SELECT
    app_version,
    app_build_id,
    client_count,
    ARRAY<STRUCT<percentile STRING, value FLOAT64>>[
      ('0.1', mozfun.glam.percentile(0.1, aggregates, metric_type)),
      ('1', mozfun.glam.percentile(1, aggregates, metric_type)),
      ('5', mozfun.glam.percentile(5, aggregates, metric_type)),
      ('25', mozfun.glam.percentile(25, aggregates, metric_type)),
      ('50', mozfun.glam.percentile(50, aggregates, metric_type)),
      ('75', mozfun.glam.percentile(75, aggregates, metric_type)),
      ('95', mozfun.glam.percentile(95, aggregates, metric_type)),
      ('99', mozfun.glam.percentile(99, aggregates, metric_type)),
      ('99.9', mozfun.glam.percentile(99.9, aggregates, metric_type))
      ] AS percentiles
  FROM pre_aggregates
)
  SELECT
    app_build_id AS build_id,
    client_count,
    percentile,
    value
  FROM percentiles_agg, UNNEST(percentiles)
  ORDER BY app_build_id ASC
