# Generated by Django 2.2.6 on 2019-11-13 00:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.IntegerField(choices=[(1, 'nightly'), (2, 'beta'), (3, 'release')])),
                ('version', models.CharField(max_length=100)),
                ('agg_type', models.IntegerField(choices=[(1, 'histogram'), (2, 'percentiles')])),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('build_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metric', models.CharField(max_length=200)),
                ('metric_key', models.CharField(blank=True, max_length=200, null=True)),
                ('client_agg_type', models.CharField(blank=True, max_length=100, null=True)),
                ('metric_type', models.CharField(max_length=100)),
                ('total_users', models.IntegerField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'aggregation',
                'managed': False,
            },
        ),
    ]
