# Generated by Django 2.2.6 on 2019-11-13 20:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aggregation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'probe',
            },
        ),
    ]
