# Generated by Django 3.0.3 on 2020-02-19 22:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_aggregation_probe"),
    ]

    operations = [
        migrations.CreateModel(
            name="BetaAggregation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "channel",
                    models.IntegerField(
                        choices=[(1, "nightly"), (2, "beta"), (3, "release")]
                    ),
                ),
                ("version", models.CharField(max_length=100)),
                (
                    "agg_type",
                    models.IntegerField(choices=[(1, "histogram"), (2, "percentiles")]),
                ),
                ("os", models.CharField(max_length=100)),
                ("build_id", models.CharField(max_length=100)),
                (
                    "process",
                    models.IntegerField(
                        choices=[(0, "*"), (1, "parent"), (2, "content"), (3, "gpu")]
                    ),
                ),
                ("metric", models.CharField(max_length=200)),
                ("metric_key", models.CharField(blank=True, max_length=200)),
                ("client_agg_type", models.CharField(blank=True, max_length=100)),
                ("metric_type", models.CharField(max_length=100)),
                ("total_users", models.IntegerField()),
                ("data", django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                "db_table": "view_glam_aggregation_beta",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NightlyAggregation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "channel",
                    models.IntegerField(
                        choices=[(1, "nightly"), (2, "beta"), (3, "release")]
                    ),
                ),
                ("version", models.CharField(max_length=100)),
                (
                    "agg_type",
                    models.IntegerField(choices=[(1, "histogram"), (2, "percentiles")]),
                ),
                ("os", models.CharField(max_length=100)),
                ("build_id", models.CharField(max_length=100)),
                (
                    "process",
                    models.IntegerField(
                        choices=[(0, "*"), (1, "parent"), (2, "content"), (3, "gpu")]
                    ),
                ),
                ("metric", models.CharField(max_length=200)),
                ("metric_key", models.CharField(blank=True, max_length=200)),
                ("client_agg_type", models.CharField(blank=True, max_length=100)),
                ("metric_type", models.CharField(max_length=100)),
                ("total_users", models.IntegerField()),
                ("data", django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                "db_table": "view_glam_aggregation_nightly",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReleaseAggregation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "channel",
                    models.IntegerField(
                        choices=[(1, "nightly"), (2, "beta"), (3, "release")]
                    ),
                ),
                ("version", models.CharField(max_length=100)),
                (
                    "agg_type",
                    models.IntegerField(choices=[(1, "histogram"), (2, "percentiles")]),
                ),
                ("os", models.CharField(max_length=100)),
                ("build_id", models.CharField(max_length=100)),
                (
                    "process",
                    models.IntegerField(
                        choices=[(0, "*"), (1, "parent"), (2, "content"), (3, "gpu")]
                    ),
                ),
                ("metric", models.CharField(max_length=200)),
                ("metric_key", models.CharField(blank=True, max_length=200)),
                ("client_agg_type", models.CharField(blank=True, max_length=100)),
                ("metric_type", models.CharField(max_length=100)),
                ("total_users", models.IntegerField()),
                ("data", django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                "db_table": "view_glam_aggregation_release",
                "abstract": False,
                "managed": False,
            },
        ),
    ]
