# Generated by Django 3.0.5 on 2020-04-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_fenix_aggregation"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesktopBetaAggregationView",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("version", models.CharField(max_length=100)),
                ("os", models.CharField(max_length=100)),
                ("build_id", models.CharField(max_length=100)),
                ("process", models.CharField(max_length=50)),
                ("metric", models.CharField(max_length=200)),
                ("metric_key", models.CharField(blank=True, max_length=200)),
                ("client_agg_type", models.CharField(blank=True, max_length=100)),
                ("metric_type", models.CharField(max_length=100)),
                ("total_users", models.IntegerField()),
                ("histogram", models.TextField(blank=True, null=True)),
                ("percentiles", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "view_glam_desktop_beta_aggregation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DesktopNightlyAggregationView",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("version", models.CharField(max_length=100)),
                ("os", models.CharField(max_length=100)),
                ("build_id", models.CharField(max_length=100)),
                ("process", models.CharField(max_length=50)),
                ("metric", models.CharField(max_length=200)),
                ("metric_key", models.CharField(blank=True, max_length=200)),
                ("client_agg_type", models.CharField(blank=True, max_length=100)),
                ("metric_type", models.CharField(max_length=100)),
                ("total_users", models.IntegerField()),
                ("histogram", models.TextField(blank=True, null=True)),
                ("percentiles", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "view_glam_desktop_nightly_aggregation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DesktopReleaseAggregationView",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("version", models.CharField(max_length=100)),
                ("os", models.CharField(max_length=100)),
                ("build_id", models.CharField(max_length=100)),
                ("process", models.CharField(max_length=50)),
                ("metric", models.CharField(max_length=200)),
                ("metric_key", models.CharField(blank=True, max_length=200)),
                ("client_agg_type", models.CharField(blank=True, max_length=100)),
                ("metric_type", models.CharField(max_length=100)),
                ("total_users", models.IntegerField()),
                ("histogram", models.TextField(blank=True, null=True)),
                ("percentiles", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "view_glam_desktop_release_aggregation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DesktopBetaAggregation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("version", models.CharField(max_length=100)),
                ("os", models.CharField(max_length=100)),
                ("build_id", models.CharField(max_length=100)),
                ("process", models.CharField(max_length=50)),
                ("metric", models.CharField(max_length=200)),
                ("metric_key", models.CharField(blank=True, max_length=200)),
                ("client_agg_type", models.CharField(blank=True, max_length=100)),
                ("metric_type", models.CharField(max_length=100)),
                ("total_users", models.IntegerField()),
                ("histogram", models.TextField(blank=True, null=True)),
                ("percentiles", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "glam_desktop_beta_aggregation",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DesktopNightlyAggregation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("version", models.CharField(max_length=100)),
                ("os", models.CharField(max_length=100)),
                ("build_id", models.CharField(max_length=100)),
                ("process", models.CharField(max_length=50)),
                ("metric", models.CharField(max_length=200)),
                ("metric_key", models.CharField(blank=True, max_length=200)),
                ("client_agg_type", models.CharField(blank=True, max_length=100)),
                ("metric_type", models.CharField(max_length=100)),
                ("total_users", models.IntegerField()),
                ("histogram", models.TextField(blank=True, null=True)),
                ("percentiles", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "glam_desktop_nightly_aggregation",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DesktopReleaseAggregation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("version", models.CharField(max_length=100)),
                ("os", models.CharField(max_length=100)),
                ("build_id", models.CharField(max_length=100)),
                ("process", models.CharField(max_length=50)),
                ("metric", models.CharField(max_length=200)),
                ("metric_key", models.CharField(blank=True, max_length=200)),
                ("client_agg_type", models.CharField(blank=True, max_length=100)),
                ("metric_type", models.CharField(max_length=100)),
                ("total_users", models.IntegerField()),
                ("histogram", models.TextField(blank=True, null=True)),
                ("percentiles", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "glam_desktop_release_aggregation",
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="desktopreleaseaggregation",
            constraint=models.UniqueConstraint(
                fields=(
                    "version",
                    "os",
                    "build_id",
                    "process",
                    "metric",
                    "metric_key",
                    "client_agg_type",
                ),
                name="desktop_release_unique_dimensions",
            ),
        ),
        migrations.AddConstraint(
            model_name="desktopnightlyaggregation",
            constraint=models.UniqueConstraint(
                fields=(
                    "version",
                    "os",
                    "build_id",
                    "process",
                    "metric",
                    "metric_key",
                    "client_agg_type",
                ),
                name="desktop_nightly_unique_dimensions",
            ),
        ),
        migrations.AddConstraint(
            model_name="desktopbetaaggregation",
            constraint=models.UniqueConstraint(
                fields=(
                    "version",
                    "os",
                    "build_id",
                    "process",
                    "metric",
                    "metric_key",
                    "client_agg_type",
                ),
                name="desktop_beta_unique_dimensions",
            ),
        ),
    ]
