# Generated by Django 3.0.5 on 2020-04-27 20:53

from django.db import migrations

from glam.api import constants


sql = []
for channel in constants.CHANNEL_NAMES.values():
    sql.extend(
        [
            f"CREATE MATERIALIZED VIEW view_glam_desktop_{channel}_aggregation AS SELECT * FROM glam_desktop_{channel}_aggregation;",
            f"CREATE UNIQUE INDEX ON view_glam_desktop_{channel}_aggregation (id);",
            f"CREATE INDEX ON view_glam_desktop_{channel}_aggregation (version);",
            f"CREATE INDEX ON view_glam_desktop_{channel}_aggregation USING HASH (metric);",
            f"CREATE INDEX ON view_glam_desktop_{channel}_aggregation USING HASH (os);",
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_desktop_models"),
    ]

    operations = [
        migrations.RunSQL(
            sql,
            reverse_sql=[
                f"DROP MATERIALIZED VIEW view_glam_desktop_{channel}_aggregation"
                for channel in constants.CHANNEL_NAMES.values()
            ],
        )
    ]
