# Generated by Django 3.0.6 on 2020-06-02 22:56

from django.db import migrations

from glam.api import constants


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_compress_json'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aggregation',
        ),
        migrations.DeleteModel(
            name='BetaAggregation',
        ),
        migrations.DeleteModel(
            name='NightlyAggregation',
        ),
        migrations.DeleteModel(
            name='ReleaseAggregation',
        ),
        migrations.RunSQL(
            sql=[
                f"DROP MATERIALIZED VIEW view_glam_aggregation_{channel}"
                for channel in constants.CHANNEL_IDS.keys()
            ],
        ),
        migrations.RunSQL(
            sql=["DROP TABLE glam_aggregation"],
        ),
    ]
