# Generated by Django 3.0.8 on 2020-07-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_fenix_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastUpdated",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=100)),
                ("last_updated", models.DateTimeField()),
            ],
        ),
    ]
