# Generated by Django 3.1.13 on 2022-03-04 01:21

from django.db import migrations, models

from glam.api import constants

sql_backup = []
for channel in constants.CHANNEL_NAMES.values():
    sql_backup.extend(
        [
            f"CREATE MATERIALIZED VIEW view_glam_desktop_{channel}_aggregation_backup AS SELECT * FROM glam_desktop_{channel}_aggregation;",
            f"CREATE UNIQUE INDEX ON view_glam_desktop_{channel}_aggregation_backup (id);",
            f"CREATE INDEX ON view_glam_desktop_{channel}_aggregation_backup (version);",
            f"CREATE INDEX ON view_glam_desktop_{channel}_aggregation_backup USING HASH (metric);",
            f"CREATE INDEX ON view_glam_desktop_{channel}_aggregation_backup USING HASH (os);",
        ]
    )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_fog_counts'),
    ]

    operations = [
    
        migrations.AddField(
            model_name='desktopbetaaggregation',
            name='total_sample',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desktopnightlyaggregation',
            name='total_sample',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desktopreleaseaggregation',
            name='total_sample',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fenixaggregation',
            name='total_sample',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fogaggregation',
            name='total_sample',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.RunSQL(
            [
                "CREATE MATERIALIZED VIEW view_glam_fenix_aggregation_backup AS SELECT * FROM glam_fenix_aggregation",
                "CREATE UNIQUE INDEX ON view_glam_fenix_aggregation_backup (id)",
                "CREATE INDEX ON view_glam_fenix_aggregation_backup (version)",
                "CREATE INDEX ON view_glam_fenix_aggregation_backup USING HASH (app_id)",
                "CREATE INDEX ON view_glam_fenix_aggregation_backup USING HASH (metric)",
                "CREATE INDEX ON view_glam_fenix_aggregation_backup USING HASH (os)",
            ],
            reverse_sql=["DROP MATERIALIZED VIEW view_glam_fenix_aggregation_backup"],
        ),
        migrations.RunSQL(
            [
                "CREATE MATERIALIZED VIEW view_glam_fog_aggregation_backup AS SELECT * FROM glam_fog_aggregation",
                "CREATE UNIQUE INDEX ON view_glam_fog_aggregation_backup (id)",
                "CREATE INDEX ON view_glam_fog_aggregation_backup (version)",
                "CREATE INDEX ON view_glam_fog_aggregation_backup USING HASH (app_id)",
                "CREATE INDEX ON view_glam_fog_aggregation_backup USING HASH (metric)",
                "CREATE INDEX ON view_glam_fog_aggregation_backup USING HASH (os)",
            ],
            reverse_sql=["DROP MATERIALIZED VIEW view_glam_fog_aggregation_backup"],
        ),

        migrations.RunSQL(
            sql_backup,
            reverse_sql=[
                f"DROP MATERIALIZED VIEW view_glam_desktop_{channel}_aggregation_backup"
                for channel in constants.CHANNEL_NAMES.values()
            ],
        ),
    ]