# Generated by Django 3.1.13 on 2022-04-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_delete_sqlite_probes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentationUsage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('PROBE_SEARCH', 'probe_search')], max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(null=True)),
                ('session_id', models.CharField(max_length=100)),
                ('probe_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'glam_instrumentation_usage',
            },
        ),
    ]
