# Generated by Django 3.1.13 on 2023-05-25 22:59

from django.db import migrations, models

from glam.api import constants

sql_create = []
sql_rename = []
sql_drop = []
for channel in constants.CHANNEL_NAMES.values():
    sql_create.extend(
        [
            f"CREATE MATERIALIZED VIEW view_glam_desktop_{channel}_aggregation_2 AS SELECT * FROM glam_desktop_{channel}_aggregation;",
            f"CREATE UNIQUE INDEX ON view_glam_desktop_{channel}_aggregation_2 (id);",
            f"CREATE INDEX ON view_glam_desktop_{channel}_aggregation_2 (version);",
            f"CREATE INDEX ON view_glam_desktop_{channel}_aggregation_2 USING HASH (metric);",
            f"CREATE INDEX ON view_glam_desktop_{channel}_aggregation_2 (os);",
        ]
    )
for channel in constants.CHANNEL_NAMES.values():
    sql_rename.extend(
        [
            f"ALTER MATERIALIZED VIEW view_glam_desktop_{channel}_aggregation rename TO view_glam_desktop_{channel}_aggregation_old;",
            f"ALTER MATERIALIZED VIEW view_glam_desktop_{channel}_aggregation_2 rename TO view_glam_desktop_{channel}_aggregation;",
        ]
    )
for channel in constants.CHANNEL_NAMES.values():
    sql_drop.extend(
        [
            f"DROP MATERIALIZED VIEW view_glam_desktop_{channel}_aggregation_old;",
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_usageinstrumentation"),
    ]

    operations = [
        migrations.AddField(
            model_name="desktopbetaaggregation",
            name="non_norm_histogram",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="desktopbetaaggregation",
            name="non_norm_percentiles",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="desktopnightlyaggregation",
            name="non_norm_histogram",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="desktopnightlyaggregation",
            name="non_norm_percentiles",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="desktopreleaseaggregation",
            name="non_norm_histogram",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="desktopreleaseaggregation",
            name="non_norm_percentiles",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunSQL(
            sql_create,
        ),
        migrations.RunSQL(
            sql_rename,
        ),
        migrations.RunSQL(
            sql_drop,
        ),
    ]
