# Generated by Django 3.1.13 on 2023-05-25 22:59

from django.db import migrations, models

from glam.api import constants

sql = []
sql_drop = []
for channel in constants.CHANNEL_NAMES.values():
    sql.extend(
        [
            f"CREATE MATERIALIZED VIEW view_glam_desktop_{channel}_aggregation AS SELECT * FROM glam_desktop_{channel}_aggregation;",
            f"CREATE UNIQUE INDEX ON view_glam_desktop_{channel}_aggregation (id);",
            f"CREATE INDEX ON view_glam_desktop_{channel}_aggregation (version);",
            f"CREATE INDEX ON view_glam_desktop_{channel}_aggregation USING HASH (metric);",
            f"CREATE INDEX ON view_glam_desktop_{channel}_aggregation (os);",
        ]
    )
for channel in constants.CHANNEL_NAMES.values():
    sql_drop.extend(
        [
            f"DROP MATERIALIZED VIEW view_glam_desktop_{channel}_aggregation;",
        ]
    )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_usageinstrumentation'),
    ]

    operations = [
        migrations.RunSQL(
            sql_drop,
            reverse_sql=[
                f"DROP MATERIALIZED VIEW view_glam_desktop_{channel}_aggregation"
                for channel in constants.CHANNEL_NAMES.values()
            ],
        ),
        migrations.AddField(
            model_name='desktopbetaaggregation',
            name='non_norm_histogram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desktopbetaaggregation',
            name='non_norm_percentiles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desktopnightlyaggregation',
            name='non_norm_histogram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desktopnightlyaggregation',
            name='non_norm_percentiles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desktopreleaseaggregation',
            name='non_norm_histogram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desktopreleaseaggregation',
            name='non_norm_percentiles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunSQL(
            sql,
            reverse_sql=[
                f"DROP MATERIALIZED VIEW view_glam_desktop_{channel}_aggregation"
                for channel in constants.CHANNEL_NAMES.values()
            ],
        )
    ]
